#!/bin/zsh
find . -type f -name __pycache__ -exec rm -rf {} \;
git config --global user.name "AesmaDiv"
git config --global user.email "jhwh.0001@gmail.com"
git add .
git commit -m "last update"
git push origin main
